name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build APK
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ElemSocial.apk